// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function JoinRoom(arg1) {
  return window['go']['main']['App']['JoinRoom'](arg1);
}

export function SendFrameData(arg1) {
  return window['go']['main']['App']['SendFrameData'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function StartStreaming() {
  return window['go']['main']['App']['StartStreaming']();
}
