// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function JoinRoom(arg1:string):Promise<string>;

export function SendFrameData(arg1:Array<number>):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function StartStreaming():Promise<void>;
